added folding setting to keep displaying the closing tag after folding
eclipse/lemminx pull request #1209
Opened 2022-05-27 20:12 UTC by JessicaJHee

Requires redhat-developer/vscode-xml/pull/714

Signed-off-by: Jessica He <jhe@redhat.com>

2022-05-27 21:03 UTC, AlexXuChen requested changes
Features working as intended:
![Peek 2022-05-27 16-57](https://user-images.githubusercontent.com/26389510/170789249-7d71a7b9-ae59-4b1c-a777-624a9cc5676a.gif)
A couple of changes, and add/change tests in https://github.com/eclipse/lemminx/blob/master/org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/services/XMLFoldingsTest.java with the setting enabled/disabled.

2022-05-28 09:56 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/settings/XMLFoldingSettings.java
> +		this.includeClosingTagInFold = DEFAULT_INCLUDE_CLOSING_TAG_IN_FOLD;
Indeed it is a good practive to have just one constructor which initialize all fields.

2022-05-28 10:07 UTC, angelozerr commented
It shoud be nice to have test with this new settings.

I suggest that you: define a new static method in
https://github.com/eclipse/lemminx/blob/3ed05cb913f471c582f6de498211a5fc104dbca9/org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/services/XMLFoldingsTest.java#L236

```java

private static void assertRanges(String[] lines, ExpectedIndentRange[] expected) {
	assertRanges(lines, expected, "", null, new XMLFoldingSettings());
}

private static void assertRanges(String[] lines, ExpectedIndentRange[] expected, XMLFoldingSettings settings) {
	assertRanges(lines, expected, "", null, settings);
}

private static void assertRanges(String[] lines, ExpectedIndentRange[] expected, String message, Integer nRanges) {
    assertRanges(lines, expected, message, nRanges, new XMLFoldingSettings());
}

private static void assertRanges(String[] lines, ExpectedIndentRange[] expected, String message, Integer nRanges, XMLFoldingSettings settings)
TextDocument document = new TextDocument(String.join("\n", lines), "test://foo/bar.json");
		DOMDocument xmlDocument = DOMParser.getInstance().parse(document, null);
		XMLLanguageService languageService = new XMLLanguageService();

		FoldingRangeCapabilities context = new FoldingRangeCapabilities();
		context.setRangeLimit(nRanges);
		settings.setCapabilities(context);
		List<FoldingRange> actual = languageService.getFoldingRanges(xmlDocument, settings);

		List<ExpectedIndentRange> actualRanges = new ArrayList<>();
		for (FoldingRange f : actual) {
			actualRanges.add(r(f.getStartLine(), f.getEndLine(), f.getKind()));
		}
		Collections.sort(actualRanges, (r1, r2) -> r1.startLine - r2.startLine);
		assertArrayEquals(expected, actualRanges.toArray(), message);
}
```

after that you can duplicate test and set your new settings includeClosingTagInFold:

```
@Test
	public void testFoldOneLevelWithincludeClosingTagInFoldAsFalse () {
		String[] input = new String[] {
			/*0*/"<html>",
			/*1*/"Hello",
			/*2*/"</html>"
		};
                XMLFoldingSettings settings = new XMLFoldingSettings ();
                settings.setIncludeClosingTagInFold(false)
		assertRanges(input,  new ExpectedIndentRange[] {r(0, 2)}, );
	}
```

Please not the test will fail, please adjust the proper ranges.

And you can do the same thing for existing tests.

2022-05-30 21:33 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/XMLFoldings.java
> +	public boolean isIncludeClosingTagInFold(XMLFoldingSettings context) {
As it is not an important method, I will move it after `getFoldingRanges` which is main entry method. More this method is used only in this class, so you can set to private. At the end, this method don't need some fields of the XMLFoldings, so I will add static, in other words : 

`private static isIncludeClosingTagInFold(XMLFoldingSettings foldingSettings)`

2022-05-30 21:35 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/settings/XMLFoldingSettings.java
> +	public static final boolean DEFAULT_INCLUDE_CLOSING_TAG_IN_FOLD = false;
this static filed is used only in this class, set it to `private`.

2022-05-30 21:37 UTC, angelozerr commented on org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/services/XMLFoldingsTest.java
> +	public void	testFoldTwoLevelWithincludeClosingTagInFoldAsTrue ()  {
remove tabs with space (`public void test...`). Do the samething for other test methods

2022-05-31 15:25 UTC, merged

2022-05-31 15:25 UTC, angelozerr commented
Great job @JessicaJHee !