Support xml.format.enforceQuoteStyle setting with experimental formatter
eclipse/lemminx pull request #1249
Opened 2022-07-07 19:45 UTC by JessicaJHee

Fixes #1239 

Signed-off-by: Jessica He <jhe@redhat.com>

2022-07-08 07:55 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/dom/DTDDeclNode.java
> +	public String getTextContent() {
Why you need this method?

2022-07-08 08:00 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMAttributeFormatter.java
> +			formatterDocument.replaceQuoteWithPreferred(attr.getNodeAttrValue().getStart(),
It seems that you assume that there are quote but what about invalid attributs

name=123"
name="123

Please write test with those usecases.

2022-07-09 13:31 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMAttributeFormatter.java
> +		return (character == SINGLE_QUOTE || character == DOUBLE_QUOTE);
private static

2022-07-09 14:14 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +	private int getIdStart(DOMDocumentType docType) {
static

2022-07-09 14:14 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +		if (docType.getPublicIdNode() != null) {
static

2022-07-09 14:18 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +		if (StringUtils.isQuoted(nodeDecl.getOwnerDocument().getText().substring(paramStart, paramEnd))) {
You can do this check by looping chatacters to avoid using substring which creates a new String instance which is not good for memory performance.

2022-07-09 14:25 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +						// <!DOCTYPE note SYSTEM "note.dtd">"
Remove last quote at the end of the line

2022-07-09 14:26 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +				int endDocType = docType.getEnd() - 1;
Please add a sample in javadoc

2022-07-09 14:27 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +			int endDocType = internalSubset.getEnd() - 1;
Please add a sample in comment

2022-07-09 14:29 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +					formatDTDNodeDecl(nodeDecl, parentConstraints, addLineSeparator, edits);
Palease add a sample in comment

2022-07-09 14:32 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +					// replace current quote with preferred quote in the case:
Could add please à sample in comment for the prévois line code with replaceLeftSpacesWithOneSpace...

2022-07-09 14:32 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +					// replace current quote with preferred quote in the case:
Could add please à sample in comment for the prévois line code with replaceLeftSpacesWithOneSpace...

2022-07-09 14:34 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/TextEditUtils.java
> +		return (character.equals(SINGLE_QUOTE) || character.equals(DOUBLE_QUOTE));
Please use isQuoted from StringUtils or define it in StringUtils

2022-07-09 14:49 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMAttributeFormatter.java
> +			if (originalValue.charAt(0) != getQuotationAsChar()
Add a sample in comment

2022-07-11 13:54 UTC, datho7561 requested changes

2022-07-11 15:26 UTC, datho7561 commented
I think that there is also a `isQuote` in StringUtils, separate from `isQuoted`, which just handles the situation you are talking about

2022-07-11 15:52 UTC, JessicaJHee commented
> I think that there is also a `isQuote` in StringUtils, separate from `isQuoted`, which just handles the situation you are talking about

Ohh I completely missed that, thank you!

2022-07-11 20:20 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +	private static int getIdStart(DOMDocumentType docType) {
I would rename with getDocTypeIdStart and same thing for getIdEnd

2022-07-11 20:23 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/format/DOMDocTypeFormatter.java
> +	}
I would return -1 instead like string index Officiel method

2022-07-14 10:06 UTC, angelozerr commented on org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/services/format/experimental/XMLFormatterQuoteStyleTest.java
> +		assertFormat(expected, expected, settings);
OK nice to have add tests. For dtd usecase I suggest that you create an issue for that. I think we should improve the dom parser but les do that in an another pr

2022-07-14 10:09 UTC, angelozerr commented
Once my comments will be fixed, the code looks good.

@datho7561 could you please test the pr too.

2022-07-14 12:53 UTC, datho7561 approved these changes
This works very well for me. Well done, Jessica! Once you've addressed Angelo's comments, I'll merge it.

2022-07-14 14:12 UTC, angelozerr commented
Once this pr will be meŕged @JessicaJHee could yiu create a pr in vscode xml in Format.md and package.json to remove comment which says that your settings is now supported.

2022-07-14 15:14 UTC, merged

2022-07-14 15:16 UTC, datho7561 commented on org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/services/format/experimental/XMLFormatterQuoteStyleTest.java
> +		assertFormat(expected, expected, settings);
@JessicaJHee Make sure to create an issue under lemminx for this