Wrap element
eclipse/lemminx pull request #1389
Opened 2022-12-05 14:55 UTC by angelozerr

Wrap element

2022-12-06 22:37 UTC, angelozerr commented
Tests exists now, @datho7561 please review it again.

2022-12-07 14:29 UTC, datho7561 commented
If I used linked editing, I can add spaces and newlines into the element name

```xml
<elt|></elt>
```

If I type in `<space>hello<enter>`, then I get:

```xml
<elt hello
></elt hello
  >
```

2022-12-07 15:09 UTC, datho7561 requested changes
If you are okay with the behaviour of the linked editing as a result of the parser changes, then I think the PR is good. However, it seems a bit buggy to me. I noticed a small typo in some documentation

2022-12-07 15:09 UTC, datho7561 commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/dom/DOMParser.java
> +					// ex : <\>
`</>`

2022-12-07 15:27 UTC, angelozerr commented
> If I used linked editing, I can add spaces and newlines into the element name

I cannot reproduce, could you do a demo please.

2022-12-07 15:28 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/dom/DOMParser.java
> +					// ex : <\>
fixed

2022-12-07 15:55 UTC, datho7561 commented
![surround-with-weird-linked-editing](https://user-images.githubusercontent.com/22376627/206227292-d7e347b6-073a-4186-a979-118a095cdc53.gif)

2022-12-07 16:36 UTC, angelozerr commented
Oh I see what you mean.  In this case you are using snippet and not linked editing range. I'm not  sure that we can control that.

If you wish to test with linked editing range support, do like your demo to generate the start / end tag element without tag and press on Escape to quit the snippet mode. Type some content in the tag and linked editing range will be activated in this case and you should not have the issue of your demo.

2022-12-07 16:56 UTC, datho7561 approved these changes
> In this case you are using snippet and not linked editing range. 

Okay. Sorry it looks like I just misunderstood what was happening. This looks good to me! Thanks, Angelo!

2022-12-07 16:58 UTC, merged