Improve ETagRequired error range
eclipse/lemminx pull request #897
Opened 2020-10-01 09:25 UTC by angelozerr

Improve ETagRequired error range

Fixes #876

Signed-off-by: azerr azerr@redhat.com

2020-10-05 13:48 UTC, angelozerr commented
This PR fixes error range for ETAgrequired, the main idea is to higlight the error from the start tag which is broken to the offset reported by Xerces:

![image](https://user-images.githubusercontent.com/1932211/95080934-20c09180-0719-11eb-9e03-2b3b00643ea7.png)

The start tag can be broken because:

 * it has not an end tag
 * it has an end tag but it contains </ which breaks the XML.

As I had to fix CloseStartTagAction which is used for several error code,this PR fixes several issues:

 * https://github.com/eclipse/lemminx/issues/900
 * https://github.com/eclipse/lemminx/issues/889
 * https://github.com/eclipse/lemminx/issues/880
 * https://github.com/eclipse/lemminx/issues/878

2020-10-05 14:01 UTC, datho7561 commented
For cases like this:
```xml
<a>
  <c><b>
</a>
```
the opening `<` of `</a>` is highlighted in the error range:

![Screenshot from 2020-10-05 10-01-02](https://user-images.githubusercontent.com/22376627/95089081-b8aa8500-06f1-11eb-921b-6885b307b6dd.png)

I find this behaviour odd, since the closing tag should appear before `</a>`. As well, `</a>` is correct; it closes the `<a>` tag.

2020-10-05 17:29 UTC, datho7561 requested changes

2020-10-08 12:39 UTC, angelozerr commented
> the opening < of </a> is highlighted in the error range:

fixed

2020-10-08 12:39 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/XMLSyntaxErrorCode.java
> +			// return XMLPositionUtility.selectChildEndTag(tag, offset, document);
fixed

2020-10-08 12:40 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/ETagUnterminatedCodeAction.java
> +* Copyright (c) 2019 Red Hat Inc. and others.
fixed

2020-10-09 08:05 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/CloseTagCodeAction.java
> +	public void doCodeAction(Diagnostic diagnostic, Range range, DOMDocument document, List<CodeAction> codeActions,
fixed and I add comments with samples for each usecases.

2020-10-09 08:06 UTC, angelozerr commented
@datho7561 please review my PR (with vscode-xml and see if my code is understandable). Thanks

2020-10-09 15:08 UTC, datho7561 requested changes

2020-10-09 15:08 UTC, datho7561 commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/CloseTagCodeAction.java
> +	public void doCodeAction(Diagnostic diagnostic, Range range, DOMDocument document, List<CodeAction> codeActions,
This method is still pretty long. Do you think its possible to split the cases for `startTagClosed == true` and `startTagClosed == false` into separate functions?

2020-10-09 16:08 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/CloseTagCodeAction.java
> +	public void doCodeAction(Diagnostic diagnostic, Range range, DOMDocument document, List<CodeAction> codeActions,
Try to fixed that, is it better?

2020-10-09 16:19 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/CloseTagCodeAction.java
> +					String insertText = initialInsertText;
fixed

2020-10-09 17:08 UTC, merged