Reloading remote schema
eclipse/lemminx pull request #911
Opened 2020-10-13 17:00 UTC by angelozerr

Reloading remote schema

See redhat-developer/vscode-xml#284

Signed-off-by: azerr <azerr@redhat.com>

2020-10-13 17:03 UTC, angelozerr commented
@BoykoAlex I'm starting to use your custom XML command support. I would like to provide some abstract class that you could use. Please tell me if you could use it. I mean https://github.com/eclipse/lemminx/pull/911/files#diff-ce0efddeef41b8881cd864523bdbfa55f5a1e310967e6b1014fce2f1fa26e273 which is an abstract command handler class which get a DOM Document from the first arguments where uri is filled with TextDocumentIdentifier.

Any feedback are welcome and it should be very nice if you could use it. Thanks!

2020-10-13 17:32 UTC, angelozerr commented
See PR https://github.com/redhat-developer/vscode-xml/pull/343 on vscode-xml side.

2020-10-13 17:48 UTC, BoykoAlex commented
@angelozerr The command I'm registering at the moment is somewhat similar to `XMLValidationAllFilesCommand`... It's not per document... The command I'm registering lets the client to send classpath change message to the server (any project in the workspace classpath change event).
However, if the command had a doc id as a parameter I'd go with `AbstractDOMDocumentCommandHandler`

2020-10-15 10:22 UTC, angelozerr commented
This PR provides 2 XML custom commands :

 * a command to validate a given XML file which evicts cache for referenced grammars and retrigger the validation
 * a command to validate all opened XML files which evict the cache.

@datho7561 you can play with this PR and redhat-developer/vscode-xml#343 it should work.

I need to write tests and improve this PR to manage dependencies of referenced grammar to evict cache for those dependencies.

2020-10-15 17:38 UTC, datho7561 commented
It seems to work during my manual testing. I think that it makes sense to do the work to evict include/imported grammars in a separate PR. Its a feature that probably won't be used as much.

2020-10-15 18:09 UTC, angelozerr commented
>  Its a feature that probably won't be used as much.

I agree, user could use the other commands to evict the full cache.

2020-10-20 16:24 UTC, angelozerr commented
@datho7561 the PR is not ready, tests has been written.

2020-10-20 18:15 UTC, datho7561 requested changes
There were a few spots where exceptions were thrown and it wasn't that clear what would cause them. Other than that, it looks good.

2020-10-20 19:07 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/model/ContentModelManager.java
> +	 * @throws IOException
fixed

2020-10-20 19:07 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/extensions/commands/ArgumentsUtils.java
> +	 * @return the object from the given index as a given class type and null
fixed

2020-10-20 19:08 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/uriresolver/CacheResourcesManager.java
> +	 * @throws IOException
fixed

2020-10-20 19:08 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/uriresolver/XMLCacheResolverExtension.java
> +	 * @throws IOException
fixed

2020-10-20 19:08 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/model/ContentModelManager.java
> +	 * @throws IOException
fixed

2020-10-20 19:09 UTC, datho7561 approved these changes

2020-10-20 19:14 UTC, merged