Symbol outline / search: Customizable display text
eclipse/lemminx pull request #913
Opened 2020-10-15 13:26 UTC by angelozerr

Symbol outline / search: Customizable display text

Fixes #220

Signed-off-by: azerr <azerr@redhat.com>

2020-10-15 13:27 UTC, angelozerr commented
To play with this PR, please use https://github.com/redhat-developer/vscode-xml/pull/344 on vscode-xml side.

See my explanation with filter at https://github.com/redhat-developer/vscode-xml/issues/220#issuecomment-708612353

2020-10-26 10:24 UTC, angelozerr commented
Please see documentation in https://github.com/redhat-developer/vscode-xml/pull/346/files#diff-a1a54c198023b2a813561e299446d0cebea6ebafef9dd59f8107aaa05f6ac057

2020-10-26 20:04 UTC, datho7561 requested changes
One other thing I noticed is that there is an NPE if an expression is missing its "xpath" element in the JSON. This means that no symbols get shown in this case.

2020-10-27 08:06 UTC, angelozerr commented on org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/services/XMLSymbolInformationsTest.java
>  	}
done

2020-10-27 10:43 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/XMLSymbolsProvider.java
> +		boolean hasChildNodes = node.hasChildNodes() || node.hasAttributes();
You are right, but I needed that to instanicate the symbols list too. My code was not clear, I updated it and I introduce a collectAttributes boolean to manage this case.

2020-10-27 18:37 UTC, datho7561 approved these changes
It is good, but there are just a few things that need to be fixed on the client side before merging.

2020-10-27 18:40 UTC, merged

2020-10-27 19:13 UTC, angelozerr commented
Thanks @datho7561 for your great review!