No completion on attributes with xs:union (XSD)
eclipse/lemminx pull request #923
Opened 2020-10-30 14:45 UTC by angelozerr

No completion on attributes with xs:union (XSD)

Fixes https://github.com/redhat-developer/vscode-xml/issues/351

Signed-off-by: azerr <azerr@redhat.com>

2020-10-30 14:56 UTC, angelozerr commented
This PR 

 * fixes redhat-developer/vscode-xml#351
 * manage documentation from xs:enumeration inside attribute value
 * manage documentation from xs:enumeration inside text node

To play with this PR, you can write the `dressSize.xsd` file:

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:simpleType name="SizeType">
		<xs:union memberTypes="DressSizeType">
			<xs:annotation>
				<xs:documentation>Size Type documentation</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="small">
						<xs:annotation>
							<xs:documentation>Small documentation</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="medium">
						<xs:annotation>
							<xs:documentation>Medium documentation</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="large" />
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="DressSizeType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="2" />
			<xs:maxInclusive value="18" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="dresssize" type="SizeType" />

	<xs:element name="dress">
		<xs:complexType>
			<xs:attribute name="size" type="SizeType" />
		</xs:complexType>
	</xs:element>

</xs:schema>
```

 * for testing xs:enumeration completion and hover inside attribute value, write this XML and play with size attribute value:

```xml
<dress
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./dressSize.xsd"
	size="large" />
```

 * for testing xs:enumeration completion and hover inside text node, write this XML:
```xml
<dresssize
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./dressSize.xsd">
	
	small
	</dresssize>
```

2020-11-03 15:21 UTC, datho7561 commented
If a blank `<xs:documentation>` is provided under enum, then instead of showing the documentation for the parent type, it doesn't show any documentation. It might be worthwhile to show the parent documentation in this case if it easy to do so.

To reproduce:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:simpleType name="SizeType">
		<xs:union memberTypes="DressSizeType">
			<xs:annotation>
				<xs:documentation>Size Type documentation</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="small">
						<xs:annotation>
							<xs:documentation></xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="medium">
						<xs:annotation>
							<xs:documentation>Medium documentation</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="large" />
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="DressSizeType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="2" />
			<xs:maxInclusive value="18" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="dresssize" type="SizeType" />

	<xs:element name="dress">
		<xs:complexType>
			<xs:attribute name="size" type="SizeType" />
		</xs:complexType>
	</xs:element>

</xs:schema>
```

Make an XML that associates with the above schema, then open the completion for a dresssize and select `small`. No documentation is shown.

2020-11-03 16:17 UTC, datho7561 requested changes

2020-11-04 14:57 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/dtd/contentmodel/CMDTDAttributeDeclaration.java
> +	public String getAttributeValueDocumentation(String value, ISharedSettingsRequest settings) {
fixed

2020-11-04 14:59 UTC, angelozerr commented
> Make an XML that associates with the above schema, then open the completion for a dresssize and select small. No documentation is shown.

It should be fixed and I wrote test for this usecase.

2020-11-04 14:59 UTC, angelozerr commented on org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/extensions/contentmodel/XMLSchemaHoverExtensionsTest.java
> +	@Test
Yes it's intentional. If attribute value documentation cannot be found we display attribute name documentation.

2020-11-04 15:23 UTC, datho7561 approved these changes

2020-11-04 15:24 UTC, merged

2020-11-04 15:31 UTC, angelozerr commented
Thanks @datho7561 for your review!