Manage namespaces / prefix validation with a settings
eclipse/lemminx pull request #961
Opened 2021-01-15 15:16 UTC by angelozerr

Manage namespaces / prefix validation with a settings

Fixes #960

Signed-off-by: azerr <azerr@redhat.com>

2021-01-15 15:28 UTC, angelozerr commented
This PR requires the vscode-xml PR https://github.com/redhat-developer/vscode-xml/pull/391 which defines the new settings `xml.validation.namespaces.enabled`

I need to write tests.

2021-01-15 15:37 UTC, angelozerr commented
Here a demo with vscode-xml:

![NamespaceValidationDemo](https://user-images.githubusercontent.com/1932211/104746693-eae76c00-574f-11eb-9d51-a0a146d6cd7b.gif)

2021-01-15 15:52 UTC, datho7561 commented
If I set `xml.validation.namespaces` to either `never` or `onNamespaceEncountered`, `prefix:bar` is still marked as an error in the demo file:
```xml
<foo>
  <prefix:bar />
</foo>
```

2021-01-15 16:06 UTC, datho7561 requested changes

2021-01-15 16:07 UTC, datho7561 commented
I think the name of the setting and the options are great.

2021-01-18 06:46 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/settings/NamespacesEnabled.java
> +public enum NamespacesEnabled {
fixed

2021-01-18 06:46 UTC, angelozerr commented on org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/settings/XMLNamespacesSettings.java
> +public class XMLNamespacesSettings {
fixed

2021-01-18 06:47 UTC, angelozerr commented
> I think the name of the setting and the options are great.

Thanks fort he feedback.

I switch my PR to real PR since I push tests.

2021-01-18 06:50 UTC, angelozerr commented
> If I set xml.validation.namespaces to either never or onNamespaceEncountered, prefix:bar is still marked as an error in the demo file:

You mean `xml.validation.namespaces.enabled`. 

Are you sure that you are consuming LemMinx from this PR? If you are sure, could you set the settings to `never`, stop and restart vsocde.

2021-01-18 15:16 UTC, datho7561 requested changes

2021-01-18 15:16 UTC, datho7561 commented on org.eclipse.lemminx/src/main/resources/META-INF/native-image/reflect-config.json
> +		}]
The namespace settings don't work in the native binary. If you add `"allDeclaredFields": true` in this JSON object, it will work.

2021-01-18 15:25 UTC, datho7561 approved these changes

2021-01-18 16:35 UTC, merged